### ISSUE TITLE
System.InvalidOperationException: 'Constructor WhackABox.Game(ApplicationOptions) was not found.'

### ISSUE THREAD

**Issue by celalaksu** [PacktPublishing/Xamarin.Forms-Projects#4]
(sory my English)
Hi. I am trying chapter08 , using vs 2019
Gives this error
System.InvalidOperationException: 'Constructor WhackABox.Game(ApplicationOptions) was not found.'

in vs 2019 no shared project than I used abstrac class

namespace WhackABox
{
    public abstract class Game:Application
    {
        public abstract void InitializeAR();

        public Game(ApplicationOptions options) : base(options)
        {
            
        }

--------------
 public class Game_Android: Game
    {
        private ARCoreComponent arCore;

        
        public Game_Android(ApplicationOptions options) : base(options)
        {
           

        }

**Comment by sonam-packt** [comment]
@celalaksu Does it worked used abstract class?

**Comment by sonam-packt** [comment]
@celalaksu Seem that your issues has been resolved. if not Please reopen the issue.

Thank you
